//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedGate.SSC.Windows.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedGate.SSC.Windows.Product.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Scripts.
        /// </summary>
        public static string BrowseContextMenu {
            get {
                return ResourceManager.GetString("BrowseContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the default browser. You can view the page by visiting {0}.
        /// </summary>
        public static string CantFindBrowserMessage {
            get {
                return ResourceManager.GetString("CantFindBrowserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open your browser.
        /// </summary>
        public static string CantFindBrowserTitle {
            get {
                return ResourceManager.GetString("CantFindBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to SQLServerCentral.
        /// </summary>
        public static string CredentialsFormTitle {
            get {
                return ResourceManager.GetString("CredentialsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLServerCentral.
        /// </summary>
        public static string ProductAuthor {
            get {
                return ResourceManager.GetString("ProductAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Scripts provides access to SQLServerCentral scripts from Management Studio.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sqlservercentral.com.
        /// </summary>
        public static string ProductHomePage {
            get {
                return ResourceManager.GetString("ProductHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ProductIcon {
            get {
                object obj = ResourceManager.GetObject("ProductIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLScriptsToolbar.
        /// </summary>
        public static string ToolbarButtonName {
            get {
                return ResourceManager.GetString("ToolbarButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Scripts.
        /// </summary>
        public static string ToolbarButtonText {
            get {
                return ResourceManager.GetString("ToolbarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse SQLServerCentral scripts.
        /// </summary>
        public static string ToolbarButtonToolTip {
            get {
                return ResourceManager.GetString("ToolbarButtonToolTip", resourceCulture);
            }
        }
    }
}
